server:
  address: ":8080"
  contextRoot: "/"
  timeout: 3000   # context timeout in seconds

cache:
  address: ":8080"
  contextRoot: "/"
  timeout: 1000
  ttlSeconds: 1000

logging:
  level: "info"
  format: "json"
  bodyLogging: "all"

providers:
  youtube:
    apiKey: "AIzaSyCAJzTJgPJzXYKCum6DOiBzzmfsNXsPIyg"
  twitch:
    clientID: "TWITCH_CLIENT_ID"
    clientSecret: "TWITCH_CLIENT_SECRET"
    redirectURI: "https://device-auth"
