server:
  address: ":8080"
  contextRoot: "/"
  timeout: 3000   # context timeout in seconds

cache:
  address: ":8080"
  contextRoot: "/"
  timeout: 1000
  ttlSeconds: 1000

logging:
  level: "info"
  format: "json"
  bodyLogging: "all"

providers:
  youtube:
    apiKey: "AIzaSyCAJzTJgPJzXYKCum6DOiBzzmfsNXsPIyg"
  twitch:
    clientID: "en8xn2aotya1v2g84nwxezhjxi1wnm"
    clientSecret: "euj6fzxi5tk9t8707fkv2t2agrhhbu"
    redirectURI: "https://device-auth"
