Server:
  Address: ":8080"
  ContextRoot: "/"
  Timeout: 30   # context timeout in seconds

Logging:
  Level: "info"
  Format: "json"
  BodyLogging: "errors"

youtube:
  apiKey: "AIzaSyCAJzTJgPJzXYKCum6DOiBzzmfsNXsPIyg"

redis:
  host: "localhost:6379"
  password: ""
  db: 0

Cache:
  TTLSeconds: 300